version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mathplus_postgres
    restart: always
    environment:
      POSTGRES_USER: mathplus_user
      POSTGRES_PASSWORD: mathplus_pass
      POSTGRES_DB: mathplus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
