-- SQL file for seeding the Course table
INSERT INTO "Course" (title, slug, description, category, price, image, "updatedAt") VALUES
('Toán Tiểu Học - Lớp 1 Cơ Bản', 'toan-tieu-hoc-lop-1', 'Giúp bé làm quen với các con số, hình học cơ bản và phát triển tư duy logic sớm.', 'Toán tiểu học', '1000000', '/images/offline_math_class.jpg', NOW()),
('Toán Tiểu Học - Lớp 5 Nâng Cao', 'toan-tieu-hoc-lop-5', 'Ôn tập và nâng cao kiến thức toán lớp 5, chuẩn bị hành trang vào lớp 6 trường điểm.', 'Toán tiểu học', '1200000', '/images/online_math_class.jpg', NOW()),
('Toán THCS - Lớp 6 Tổng Ôn', 'toan-thcs-lop-6', 'Hệ thống hóa kiến thức đầu cấp, giúp học sinh nắm vững phương pháp giải các dạng bài tập mới.', 'Toán THCS', '1500000', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', NOW()),
('Toán THCS - Lớp 9 Ôn thi vào 10', 'toan-thcs-lop-9', 'Lộ trình ôn tập chuyên sâu, bám sát cấu trúc đề thi vào lớp 10 của các trường THPT.', 'Toán THCS', '2000000', '/images/offline_math_class.jpg', NOW()),
('Toán PTTH - Lớp 10 Định Hướng', 'toan-ptth-lop-10', 'Làm quen với đại số và hình học không gian, xây dựng nền tảng vững chắc cho 3 năm cấp 3.', 'Toán PTTH', '2200000', 'https://toan.vn/wp-content/uploads/2025/01/nhung-kien-thuc-dai-so-lop-7-hoc-sinh-can-nam-vung-scaled.jpg', NOW()),
('Toán PTTH - Lớp 11 Chuyên Đề', 'toan-ptth-lop-11', 'Tập trung vào các chuyên đề khó như Lượng Giác, Tổ Hợp Xác Suất, Hình Không Gian.', 'Toán PTTH', '2500000', '/images/online_math_class.jpg', NOW()),
('Luyện thi Đại học - Toán 12 Cơ Bản', 'luyen-thi-dai-hoc-toan-12-co-ban', 'Ôn luyện bám sát cấu trúc đề thi tốt nghiệp THPT, đảm bảo mục tiêu 7-8 điểm.', 'Luyện thi đại học', '3000000', '/images/offline_math_class.jpg', NOW()),
('Luyện thi Đại học - Toán 12 Nâng Cao 9+', 'luyen-thi-dai-hoc-toan-12-nang-cao', 'Khóa học trọng điểm giúp học sinh hệ thống toàn bộ kiến thức, rèn kỹ năng giải đề khó để đạt 9+.', 'Luyện thi đại học', '4000000', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', NOW());

-- SQL file for seeding the Teacher table
INSERT INTO "Teacher" (name, avatar, bio, role, exp, students, "updatedAt") VALUES
('Thầy Dũng Toán', 'https://toan.vn/wp-content/uploads/2026/07/Dang-Huy-Hoang-Toanvn.jpg', 'Khóa học Toán chuyên sâu dành cho học sinh muốn chinh phục điểm 9+ và thi học sinh giỏi.', 'Chuyên gia Luyện thi 9+', '15 năm', '5000+', NOW()),
('Thầy Trần Hồng Hà & Thầy Nguyễn Văn Dũng', '', 'Khóa học môn Toán (Chinh phục điểm 8.5+ đến 10).', 'Tổ trưởng chuyên môn', '12 năm', '3000+', NOW()),
('Thầy Thanh & Cô Linh', '', 'Khóa học Toán tư duy & Luyện thi chuyển cấp (Lớp 5 lên 6).', 'Giáo viên Khối Tiểu Học', '8 năm', '2000+', NOW()),
('Thầy Tùng & Thầy Dũng', 'https://toan.vn/wp-content/uploads/2026/07/Truong-quoc-dat-toanvn.jpg', 'Chuyên gia luyện thi Toán THPT, bám sát đề thi đại học với phương pháp giải trắc nghiệm siêu tốc.', 'Giáo viên Toán THPT', '10 năm', '4500+', NOW()),
('Cô Lan Anh & Cô Minh Châu', '', 'Đồng hành cùng học sinh mất gốc, củng cố nền tảng kiến thức, lấy lại tự tin với môn Toán THCS.', 'Giáo viên Khối THCS', '7 năm', '1500+', NOW());


-- Insert Fake Success Stories

INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Nguyễn Minh Nguyệt', 'Bí kíp chinh phục trường top đầu Hà Nội', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn8-284x284.jpg', 'on-thi-vao-lop-10-chia-se-bi-kip-chinh-phuc-truong-top-dau-ha-noi', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Đức Minh', 'Bí quyết đạt 9 điểm Toán', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/thi-toan-vao-10-284x284.jpg', 'thi-toan-vao-10-bi-quyet-dat-9-diem-toan', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Duy Hưng', 'Hành trình đạt 9,75 điểm: Kinh nghiệm ôn thi Toán vào lớp 10', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn12-284x284.jpg', 'hanh-trinh-dat-975-diem-kinh-nghiem', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Học sinh lớp 11', 'Bí quyết đạt 9,9 điểm không nằm ở bài khó', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/gioi-toan-lop-11-284x284.jpg', 'gioi-toan-lop-11-bi-quyet-dat-99-diem', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Học sinh giỏi TP', 'Thi đỗ trường THPT chuyên Chu Văn An bằng bản lĩnh', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn1-284x284.jpg', 'thi-do-truong-thpt-chuyen-chu-van-an', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Ngô Ái Linh', 'Bứt phá 9.0 điểm Toán nhờ hành trình luyện thi vào lớp 10 hiệu quả', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/z7962878671086_6befbeeedf289b163fb6925d6f6d8ee1-384x248.jpg', 'vinh-danh-ngo-ai-linh-but-pha-9-0', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Minh Huyền', 'Đạt 9,25 điểm Toán thi vào lớp 10: bật mí bí quyết', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn5-284x284.jpg', 'dat-925-diem-toan-vao-lop-10', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Học sinh Toán', 'Hành trình chinh phục Trường THPT Nguyễn Thị Minh Khai', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn4-284x284.jpg', 'hanh-trinh-chinh-phuc-truong-thpt-nguyen-thi-minh-khai', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Học sinh lớp 5', 'Giỏi Toán lớp 5 - Bí quyết nhờ thay đổi tư duy học tập', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/gioi-toan-lop-5-284x284.jpg', 'gioi-toan-lop-5-bi-quyet', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Phạm Minh Đăng', 'Học bổng 100% trường Quốc Tế', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn8-284x284.jpg', 'hoc-bong-100-truong-quoc-te', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Trần An', 'Đạt 10 điểm tuyệt đối môn Toán thi tốt nghiệp THPT', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/thi-toan-vao-10-284x284.jpg', 'dat-10-diem-tuyet-doi-toan-thpt', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Lê Hoàng', 'Chinh phục kỳ thi HSG Quốc Gia môn Toán', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn12-284x284.jpg', 'chinh-phuc-hsg-quoc-gia', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Vũ Thanh Tâm', 'Từ học sinh trung bình đến 9+ thi Đại Học', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/gioi-toan-lop-11-284x284.jpg', 'tu-trung-binh-den-9-diem-dai-hoc', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Hồ Tuấn', 'Kinh nghiệm ôn thi vượt ải chuyên Ams', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn1-284x284.jpg', 'kinh-nghiem-vuot-ai-chuyen-ams', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;
INSERT INTO \"SuccessStory\" (\"studentName\", \"achievement\", \"excerpt\", \"content\", \"imageUrl\", \"slug\", \"createdAt\", \"updatedAt\") VALUES ('Nguyễn Lan Anh', 'Tuyệt chiêu ôn tập Toán học thần tốc trong 3 tháng', 'Chia sẻ về hành trình vượt khó và bí kíp giúp đạt được thành tích cao trong môn Toán.', '<p>Nội dung chi tiết câu chuyện...</p>', 'https://toan.vn/wp-content/uploads/2026/06/toanvn5-284x284.jpg', 'tuyet-chieu-on-tap-toan-than-toc', NOW(), NOW()) ON CONFLICT (\"slug\") DO NOTHING;

-- Insert Fake Blog Posts
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 1', 'bai-viet-mau-so-1', '<p>Đây là nội dung chi tiết của bài viết số 1. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 2', 'bai-viet-mau-so-2', '<p>Đây là nội dung chi tiết của bài viết số 2. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 3', 'bai-viet-mau-so-3', '<p>Đây là nội dung chi tiết của bài viết số 3. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 4', 'bai-viet-mau-so-4', '<p>Đây là nội dung chi tiết của bài viết số 4. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 5', 'bai-viet-mau-so-5', '<p>Đây là nội dung chi tiết của bài viết số 5. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 6', 'bai-viet-mau-so-6', '<p>Đây là nội dung chi tiết của bài viết số 6. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 7', 'bai-viet-mau-so-7', '<p>Đây là nội dung chi tiết của bài viết số 7. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 8', 'bai-viet-mau-so-8', '<p>Đây là nội dung chi tiết của bài viết số 8. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 9', 'bai-viet-mau-so-9', '<p>Đây là nội dung chi tiết của bài viết số 9. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Post" ("title", "slug", "content", "image", "published", "createdAt", "updatedAt") VALUES ('Bài viết mẫu về phương pháp học Toán số 10', 'bai-viet-mau-so-10', '<p>Đây là nội dung chi tiết của bài viết số 10. Học toán cần sự kiên nhẫn và phương pháp đúng đắn...</p>', 'https://toan.vn/wp-content/uploads/2025/06/z6654844451158_4c348eebf8267220e5db3fe8fec2afb2.jpg', true, NOW(), NOW()) ON CONFLICT ("slug") DO NOTHING;
